### ISSUE TITLE
Responsiveness to be added for mobile view

### ISSUE THREAD

**Issue by yashsehgal** [muacm/muacm_website#10]
Responsiveness to be added to the website for the mobile users - This will make the user experience more reliable.
Pages in which responsive CSS has to be added are listed below.

- [x] Home Page
- [x] Events Page
- [x] Teams Page
- [x] Blogs Page
- [x] Header Component
- [x] Footer Component

**Comment by NikhilSharma03** [comment]
Add responsive css into Team page. Can you assign this issue to me?

**Comment by yashsehgal** [comment]
Alright @NikhilSharma03, you can work on this issue 👍🏽

**Comment by NikhilSharma03** [comment]
Thank you @yashsehgal

**Comment by NikhilSharma03** [comment]
@yashsehgal can you please check the PR.

**Comment by yashsehgal** [comment]
Sure! I will review it 👍🏽

**Comment by yashsehgal** [comment]
I would say @NikhilSharma03, You did an amazing job there. Thanks for your contributions to this site 😃

**Comment by yashsehgal** [comment]
The final changes are made and the site is now perfectly responsive 👍🏽 
Grear work @NikhilSharma03 and also me (@yashsehgal) 😅

**Comment by NikhilSharma03** [comment]
@yashsehgal Thank you so much. Let me know if there are any changes you want to make. I will be more than happy to help.
