### ISSUE TITLE
Images are not loading in the card components

### ISSUE THREAD

**Issue by yashsehgal** [muacm/muacm_website#3]
As there are so many profile images of our team members we can't import each and everyone - This will make the code non-manageable. Instead, We are trying to use the `require()` to use the path to load the images. 

What we are doing is using a JSON file to store the card data including the Images' path but the images are not loading.

![image](https://user-images.githubusercontent.com/62352288/118144538-3245e680-b42a-11eb-9a36-0db411936c73.png)
This is how it's looking as of now. If someone can solve this and tell us the correct path we need to use then it would be great.

For trying you can try my photo, It's saved as `yash.jpg` in the file `src/utils/images/yash.jpg` and my card is highlighted below.
![image](https://user-images.githubusercontent.com/62352288/118145099-d92a8280-b42a-11eb-97b1-ce565a8b22c1.png)

**Comment by yashsehgal** [comment]
If anyone thinks that he/she/they can solve this issue and want some more information/explanation then feel free to ask your queries.

**Comment by NikhilSharma03** [comment]
Hey yash can you assign this issue to me?

**Comment by yashsehgal** [comment]
> Hey yash can you assign this issue to me?

Sure thing @NikhilSharma03 👍🏽

**Comment by akshayDatacode** [comment]
@NikhilSharma03 what's your approach to solve this issue?

**Comment by yashsehgal** [comment]
> @NikhilSharma03 what's your approach to solve this issue?

Hey @akshayDatacode you can refer to this PR (https://github.com/muacm/muacm_website/pull/4)
